In [3]:
#Load General Library
import numpy as np
import matplotlib as mp 
import pandas as pd
import matplotlib.pyplot as plt
from ipywidgets import interact

# Load Sklearn libraries
from sklearn.tree import DecisionTreeClassifier 
from sklearn.model_selection import train_test_split 
from sklearn import metrics
from sklearn import linear_model
from sklearn import preprocessing                                                                                                       
from sklearn import utils
from sklearn.metrics import classification_report, confusion_matrix

In [4]:
#Import data
weather = pd.read_excel (r'D:\Universitas Indonesia\Semester 6\Pemodelan dan Pembelajaran Mesin\Code\5.Classification\dataset.xlsx')

x = weather.iloc[:, 1:7]
y = weather.iloc[:, 0]

scaler = preprocessing.StandardScaler()
x = scaler.fit_transform(x)

In [5]:
weather['Summary'].value_counts()

# Partly Cloudy 1
# Mostly Cloudy 2
# Overcast 3
# Foggy 4
# Clear 5
# Breezy and Partly Cloudy 6


Mostly Cloudy    188
Partly Cloudy    162
Overcast          90
Foggy             33
Clear             27
Name: Summary, dtype: int64

In [6]:
#Data Splitting
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.3, random_state=62)


In [7]:
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(x_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(x_test)

In [8]:
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.6333333333333333


In [9]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 5  0  0  0  4]
 [ 0  9  0  0  0]
 [ 2  0 29  9 17]
 [ 0  1  2 23  4]
 [ 2  0 12  2 29]]
               precision    recall  f1-score   support

        Clear       0.56      0.56      0.56         9
        Foggy       0.90      1.00      0.95         9
Mostly Cloudy       0.67      0.51      0.58        57
     Overcast       0.68      0.77      0.72        30
Partly Cloudy       0.54      0.64      0.59        45

     accuracy                           0.63       150
    macro avg       0.67      0.70      0.68       150
 weighted avg       0.64      0.63      0.63       150

